### ISSUE TITLE
6.0 下闪退

### ISSUE THREAD

**Issue by xuefer** [scola/birthday#3]
```
11-21 23:43:54.086 12592 12592 E AndroidRuntime: FATAL EXCEPTION: main
11-21 23:43:54.086 12592 12592 E AndroidRuntime: Process: com.google.android.gms.ui, PID: 12592
11-21 23:43:54.086 12592 12592 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=over
lay:system}
11-21 23:43:54.086 12592 12592 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.common.account.SimpleAccount
PickerActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-21 23:43:54.086 12592 12592 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at aae.o(:com.google.android.gms:3343)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at aae.c(:com.google.android.gms:167)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at com.google.android.chimera.appcompat.AppCompatActivity.onPostCreate(:com.google.android.gms:95)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at com.google.android.chimera.Activity.publicOnPostCreate(:com.google.android.gms:501)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at com.google.android.chimera.container.ActivityProxy.onPostCreate(:com.google.android.gms:668)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1189)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
11-21 23:43:54.086 12592 12592 E AndroidRuntime:        ... 10 more
11-21 23:43:54.088  1193  4605 W ActivityManager:   Force finishing activity com.google.android.gms/.common.account.SimpleAccountPickerActivity
11-21 23:43:54.091  1193  4605 W ActivityManager:   Force finishing activity io.github.scola.birthday/.BirthdayListActivity
```

**Comment by scola** [comment]
Thanks for reporting this issue, I reproduced this problem.
Now I'm thinking about switching to android studio project to fix it

**Comment by xuefer** [comment]
i've just created a pull request at https://github.com/scola/birthday/pull/5
i have no idea but it run correctly after building with new sdk and libraries, except i don't have the right key with authorization to use calendar API of google "cloud"

i still think it easier to use calendar provider but you're more familiar with them than me

**Comment by scola** [comment]
fixed this issue after change to android studio 
but the apk size 700k -> 6M

**Comment by xuefer** [comment]
i suppose it is the support lib.
can you share me with your release apk so i can enjoy it a little bit?

**Comment by scola** [comment]
enjoy it
debug apk
https://drive.google.com/file/d/0ByEmKcn50qJ0NWU1anVBdDlJblk/view?usp=docslist_api

**Comment by xuefer** [comment]
ah.. yes, the release build might be a lot smaller because debug build comes with debugging features, especially the "edit & continue" feature (well, i forgot the term)
thanks for the app. it works like a charm

**Comment by scola** [comment]
I will upload release version on google play
Thanks for your contribute
